import * as Bootstrap from 'react-bootstrap';
import { Link as RouterLink } from 'react-router';
export declare const ControlLabel: typeof Bootstrap.ControlLabel;
export declare const FormControl: Bootstrap.FormControlClass;
export declare const Pagination: __React.ClassicComponentClass<Bootstrap.PaginationProps>;
export declare const HelpBlock: typeof Bootstrap.HelpBlock;
export declare const FormGroup: typeof Bootstrap.FormGroup;
export declare const Checkbox: typeof Bootstrap.Checkbox;
export declare const Button: __React.ClassicComponentClass<Bootstrap.ButtonProps>;
export declare const Modal: Bootstrap.ModalClass;
export declare const Panel: __React.ClassicComponentClass<Bootstrap.PanelProps>;
export declare const Table: __React.ClassicComponentClass<Bootstrap.TableProps>;
export declare const Radio: typeof Bootstrap.Radio;
export declare const Form: typeof Bootstrap.Form;
export declare const Grid: __React.ClassicComponentClass<Bootstrap.GridProps>;
export declare const Col: __React.ClassicComponentClass<Bootstrap.ColProps>;
export declare const Row: __React.ClassicComponentClass<Bootstrap.RowProps>;
export declare const Link: typeof RouterLink;
export declare const ReCaptcha: any;
