/// <reference types="react" />
import * as React from 'react';
import * as Router from 'react-router-dom';
import * as Bootstrap from 'react-bootstrap';
export declare const ControlLabel: React.ComponentClass<Bootstrap.ControlLabelProps>;
export declare const FormControl: React.ComponentClass<Bootstrap.FormControlProps>;
export declare const Pagination: React.ComponentClass<Bootstrap.PaginationProps>;
export declare const HelpBlock: React.ComponentClass<Bootstrap.HelpBlockProps>;
export declare const FormGroup: React.ComponentClass<Bootstrap.FormGroupProps>;
export declare const Checkbox: React.ComponentClass<Bootstrap.CheckboxProps>;
export declare const Button: React.ComponentClass<Bootstrap.ButtonProps>;
export declare const Modal: React.ComponentClass<Bootstrap.ModalProps>;
export declare const ModalBody: React.ComponentClass<Bootstrap.ModalBodyProps>;
export declare const ModalFooter: React.ComponentClass<Bootstrap.ModalFooterProps>;
export declare const ModalHeader: React.ComponentClass<Bootstrap.ModalHeaderProps>;
export declare const Panel: React.ComponentClass<Bootstrap.PanelProps>;
export declare const Table: React.ComponentClass<Bootstrap.TableProps>;
export declare const Radio: React.ComponentClass<Bootstrap.RadioProps>;
export declare const Form: React.ComponentClass<Bootstrap.FormProps>;
export declare const Grid: React.ComponentClass<Bootstrap.GridProps>;
export declare const Col: React.ComponentClass<Bootstrap.ColProps>;
export declare const Row: React.ComponentClass<Bootstrap.RowProps>;
export declare const Link: React.ComponentClass<Router.LinkProps>;
export declare const ReCaptcha: any;
