import { CSS } from '../interfaces';
export declare const removeMarginAndPadding: CSS;
export declare const pullRight: CSS;
export declare const pullLeft: CSS;
export declare const defaultPanelContainer: CSS;
export declare const listStyle: CSS;
export declare const listContainer: CSS;
export declare const listItem: CSS;
export declare const defaultInputStyle: CSS;
export declare const defaultFooterContainer: CSS;
export declare const defaultTableStyle: CSS;
